apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hbuei9yqo-go 
  janus-idp.io/tekton: hbuei9yqo-go
  backstage.io/kubernetes-id: hbuei9yqo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbuei9yqo-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml